#!/usr/bin/env bash
# Write/Edit guard. Runs as a PreToolUse hook for Edit and Write tools.
# Blocks edits to files that should only change via an explicit Decision:
#   - package.json (dependencies / scripts changes)
#   - pnpm-lock.yaml (regenerated only via approved pnpm install/add)
#   - .github/workflows/* (CI config — security surface)
#   - .env, .env.* (secrets)
#   - .claude/settings.json, .claude/settings.local.json (runtime policy)
#
# Receives the tool-call payload on stdin as JSON. Exit 2 to deny.

set -euo pipefail

INPUT="$(cat)"
TOOL="$(printf '%s' "$INPUT" | jq -r '.tool_name // empty')"
FILE_PATH="$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // empty')"

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Normalize to a repo-relative path. Compare against the basename + suffix patterns.
case "$FILE_PATH" in
  */package.json|package.json)
    echo "BLOCKED by .claude/hooks/write-guard.sh: edits to package.json require a Decision (deps/scripts)." >&2
    echo "  tool: $TOOL  path: $FILE_PATH" >&2
    echo "  override: ask the user to grant explicit one-time permission." >&2
    exit 2 ;;
  */pnpm-lock.yaml|pnpm-lock.yaml|*/package-lock.json|package-lock.json|*/yarn.lock|yarn.lock)
    echo "BLOCKED: lockfiles are regenerated by approved 'pnpm install' or 'pnpm add' (P6 with Decision)." >&2
    echo "  tool: $TOOL  path: $FILE_PATH" >&2
    exit 2 ;;
  */.github/workflows/*|.github/workflows/*)
    echo "BLOCKED: edits to .github/workflows/ require a Decision (CI / security surface, P7)." >&2
    echo "  tool: $TOOL  path: $FILE_PATH" >&2
    exit 2 ;;
  */.env|.env|*/.env.*|.env.*)
    echo "BLOCKED: writing to .env files is not permitted (secrets surface)." >&2
    echo "  tool: $TOOL  path: $FILE_PATH" >&2
    exit 2 ;;
  */.claude/settings.json|.claude/settings.json|*/.claude/settings.local.json|.claude/settings.local.json)
    echo "BLOCKED: edits to .claude/settings.json change agent permissions — require a Decision." >&2
    echo "  tool: $TOOL  path: $FILE_PATH" >&2
    exit 2 ;;
esac

exit 0
