import type { ObservedZone, VisualBeat } from "@/lib/observed-playback-reducer";

/**
 * Pure render model for the ObservedBeatTimeline.
 *
 * Splitting the data-shaping out of the `.tsx` (the same pattern as
 * `timelinePosition` vs `PhaseTimeline`) keeps it unit-testable in vitest's
 * node environment and keeps the component a thin presentational layer.
 *
 * Privacy by construction: this model is built **only** from `VisualBeat`
 * fields. `VisualBeat` carries no raw payload — its `label` is generated by
 * the reducer from action + count, never from message/command/stderr text.
 * So any view built here is content-free, and the component (which renders
 * only this model) cannot leak sensitive content. The privacy test asserts
 * this end-to-end: secrets in source events never reach the serialized view.
 */

/** Canonical lane order. `activity` is the meta lane (compaction / note). */
export const ZONE_ORDER: readonly ObservedZone[] = [
  "reading",
  "coding",
  "testing",
  "thinking",
  "human",
  "outbox",
  "activity",
];

export const ZONE_LABEL: Record<ObservedZone, string> = {
  reading: "Reading",
  coding: "Coding",
  testing: "Testing",
  thinking: "Thinking",
  human: "Human",
  outbox: "Outbox",
  activity: "Activity",
};

export interface ZoneLane {
  zone: ObservedZone;
  label: string;
  beats: VisualBeat[];
}

export interface BeatDetail {
  id: string;
  zone: ObservedZone;
  zoneLabel: string;
  action: VisualBeat["action"];
  severity: VisualBeat["severity"];
  label: string;
  /** Total raw events folded in (drill-down count). */
  eventCount: number;
  /** Action-signal count (what the label is based on). */
  signalCount: number;
  startTs: string;
  endTs: string;
  /** Literal event ids for drill-down — ids only, never payload content. */
  eventIds: string[];
}

export interface TimelineView {
  summary: { beatCount: number; eventCount: number };
  /** Beats in time order — the "flow". */
  sequence: VisualBeat[];
  /** Populated zones only, in canonical order — the "where time went". */
  lanes: ZoneLane[];
  /** The drill-down detail for the selected beat, or null. */
  selected: BeatDetail | null;
}

export function beatDetail(beat: VisualBeat): BeatDetail {
  return {
    id: beat.id,
    zone: beat.zone,
    zoneLabel: ZONE_LABEL[beat.zone],
    action: beat.action,
    severity: beat.severity,
    label: beat.label,
    eventCount: beat.eventCount,
    signalCount: beat.signalCount,
    startTs: beat.startTs,
    endTs: beat.endTs,
    eventIds: [...beat.eventIds],
  };
}

/**
 * Build the full render model from a beat sequence and an optional selection.
 * Pure and deterministic.
 */
export function buildTimelineView(
  beats: VisualBeat[],
  selectedId?: string | null,
): TimelineView {
  const eventCount = beats.reduce((n, b) => n + b.eventCount, 0);

  const byZone = new Map<ObservedZone, VisualBeat[]>();
  for (const beat of beats) {
    const list = byZone.get(beat.zone);
    if (list) list.push(beat);
    else byZone.set(beat.zone, [beat]);
  }

  const lanes: ZoneLane[] = ZONE_ORDER.filter((z) => byZone.has(z)).map((zone) => ({
    zone,
    label: ZONE_LABEL[zone],
    beats: byZone.get(zone)!,
  }));

  const selectedBeat = selectedId ? beats.find((b) => b.id === selectedId) : undefined;

  return {
    summary: { beatCount: beats.length, eventCount },
    sequence: beats,
    lanes,
    selected: selectedBeat ? beatDetail(selectedBeat) : null,
  };
}
